### ISSUE TITLE
[BUG] OpenMP build error

### ISSUE THREAD

**Issue by latesnow** [HExSA-Lab/nautilus#29]
**Describe the bug**
Nautilus does not compile with OPENMP runtime support. Looks like it's missing a header file.

I'm not building with clang openmp support.

My build produces the following errors:
```
In file included from src/arch/x64/init.c:149:
include/rt/openmp/openmp.h:28:10: fatal error: rt/openmp/omp/omp.h: No such file or directory
 #include <rt/openmp/omp/omp.h>
          ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by PeterDinda** [comment]
This isn't exactly a bug.   The libopenmp-compatible runtime does not exist yet.   The scaffolding is in to use it, but that's it.   Basically, the idea is that you enable openmp, then you select an implementation of it.   The only implementation that currently exists in the repo is the GNU-compatible one.   

For now, only the GNU-compatible (GOMP) RT has an implementation.  Select that in the config and and it'll compile:    Runtimes->OpenMP->Open MP RT-> GNU-compatible (GOMP)

If anyone else would like to work on the libopenmp-compatible (or Simone's Virgil-compatible RT) , I can figure out a way to give you access to the work-in-progress code.
